name: uup-cli
description: cli client uploader for uup.
version: 1.0.0
homepage: https://uup.bugs.today
environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  cryptography:
    git:
      url: https://github.com/CDDelta/cryptography/
      ref: web-key-fix
      path: cryptography
  http: ^0.12.2
  uuid: ^2.2.2
  filesize: ^1.0.4
  args: ^1.6.0
  mime_type: ^0.3.2
  path: ^1.7.0
  ansicolor: ^1.0.5

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
  
dependency_overrides:
  meta: 1.6.0
