name: Build on Push

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: uup-linux.bin
          - os: macOS-latest
            output-name: uup-macos.bin
          - os: windows-latest
            output-name: uup-windows.exe

    steps:
      - uses: actions/checkout@v1
      - uses: DanTup/gh-actions/setup-dart@master
      - run: mkdir build
      - run: pub get
      - run: dart compile exe bin/main.dart -v -o build/${{ matrix.output-name }}
      - uses: actions/upload-artifact@v1
        with:
          name: native-executables
          path: build
